version: '3'
services:
  ranger-kafka:
    build:
      context: .
      dockerfile: Dockerfile.ranger-kafka
      args:
        - KAFKA_VERSION=${KAFKA_VERSION}
        - RANGER_VERSION=${RANGER_VERSION}
    image: ranger-kafka
    container_name: ranger-kafka
    hostname: ranger-kafka.example.com
    stdin_open: true
    tty: true
    networks:
      - ranger
    ports:
      - "6667:6667"
    depends_on:
      ranger:
        condition: service_started
      ranger-zk:
        condition: service_started
    environment:
      - KAFKA_VERSION
      - RANGER_VERSION
    volumes:
      - ./server.properties:/opt/kafka_2.12-2.5.0/config/server.properties
      - ./server.properties:/opt/kafka/config/server.properties
      - ./client.properties:/opt/kafka_2.12-2.5.0/config/client.properties
      - ./client.properties:/opt/kafka/config/client.properties
      - ./kafka-authentication/keystore:/opt/kafka_2.12-2.5.0/config/keystore
      - ./kafka-authentication/keystore:/opt/kafka/config/keystore
      - ./kafka-authentication/truststore:/opt/kafka_2.12-2.5.0/config/truststore
      - ./kafka-authentication/truststore:/opt/kafka/config/truststore
      - ./kafka-authentication/kafka_server_jaas.conf:/opt/kafka_2.12-2.5.0/config/kafka_server_jaas.conf
      - ./kafka-authentication/kafka_server_jaas.conf:/opt/kafka/config/kafka_server_jaas.conf
      - ./scripts/ranger-kafka-plugin-install.properties:/opt/ranger/ranger-kafka-plugin/install.properties
      - ./scripts/ranger-kafka-plugin-install.properties:/opt/ranger/ranger-3.0.0-SNAPSHOT-kafka-plugin/install.properties

networks:
  ranger:
    name: rangernw
